FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive 

SHELL ["/bin/bash", "-c"]

# Install OS packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    curl ca-certificates git bzip2 procps python3 python3-dev python3-pip python-is-python3 \
    && rm -rf /var/lib/apt/lists/*

# Install PyTorch
RUN pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113

# Install Cellbender from source
RUN git clone --depth 1 --branch v0.3.2 https://github.com/broadinstitute/CellBender.git /opt/cellbender \
    && pip install /opt/cellbender --no-cache-dir \
    && rm -rf /tmp/*

# Install OS packages for QC script
RUN apt-get update && apt-get install -y liblzma-dev libbz2-dev zlib1g libpng-dev libxml2-dev \
    gfortran libglpk-dev libhdf5-dev libcurl4-openssl-dev img2pdf wget libreadline8

# Install R for QC script
ARG R_VERSION=4.3.1

RUN wget https://cdn.rstudio.com/r/ubuntu-2204/pkgs/r-${R_VERSION}_1_amd64.deb && \
    apt-get update -qq && \
    apt-get install -f -y ./r-${R_VERSION}_1_amd64.deb && \
    ln -s /opt/R/${R_VERSION}/bin/R /usr/bin/R && \
    ln -s /opt/R/${R_VERSION}/bin/Rscript /usr/bin/Rscript && \
    ln -s /opt/R/${R_VERSION}/lib/R /usr/lib/R && \
    rm r-${R_VERSION}_1_amd64.deb && \
    rm -rf /var/lib/apt/lists/*


# Install R packages for QC script
RUN Rscript -e "install.packages(c('argparse', 'stringr', 'hdf5r', 'Matrix'), repos='https://cloud.r-project.org/')"

# Copy Dockerfile to the container
COPY Dockerfile /docker/
RUN chmod -R 755 /docker